version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: cssnano
    versions:
    - 5.0.1
  - dependency-name: npm
    versions:
    - 6.14.11
    - 7.10.0
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.3
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: "@wordpress/eslint-plugin"
    versions:
    - 8.0.1
    - 9.0.1
    - 9.0.2
  - dependency-name: "@wordpress/browserslist-config"
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: "@wordpress/dependency-extraction-webpack-plugin"
    versions:
    - 3.0.0
    - 3.1.1
  - dependency-name: classnames
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: postcss-import
    versions:
    - 14.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: stylelint
    versions:
    - 13.11.0
    - 13.12.0
  - dependency-name: replace-in-file
    versions:
    - 6.2.0
  - dependency-name: prompt
    versions:
    - 1.1.0
  - dependency-name: "@wordpress/prettier-config"
    versions:
    - 1.0.1
  - dependency-name: release-it
    versions:
    - 14.4.1
  - dependency-name: "@wordpress/babel-plugin-import-jsx-pragma"
    versions:
    - 3.0.1
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: "@wordpress/babel-preset-default"
    versions:
    - 5.0.0
  - dependency-name: browserslist
    versions:
    - 4.16.1
