dist: trusty

language: php
php:
  - 7

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache

install:
  - nvm install --lts
  - composer install
  - npm install

script:
  - npx grunt lint
  - npx grunt deploy
